commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.show_page, name = "show_page"),
    
]

mail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

project3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail.urls'))
]

query/urls.py
from django.urls import path
from . import views

app_name = "query"
urlpatterns = [
    path("", views.index, name = "index"),
    path("create_page", views.create_page, name = "create_page"),
    path("edit_page", views.edit_page, name = "edit_page"),
    path("random_page", views.random_page, name = "random_page"),
    path("search", views.search, name = "search"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('query/', include("query.urls")),
    path('wiki/', include("encyclopedia.urls")),
    # path('', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render

from . import util
import markdown


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def show_page(request, title):

    try:
        # print(util.get_entry(title), "hi")
        content = markdown.markdown( util.get_entry(title) )
    except AttributeError:
        return render(request, "encyclopedia/massage.html",{
        'title' : 'No Page Found',
        'massage': 'Error 404! Nothing Found On This Entry'
    })
    
    return render(request, "encyclopedia/showpage.html", {
        'content' : content,
        'title' : title
    })

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> 
                <a href="{% url 'encyclopedia:show_page' title=entry %}"> {{entry}} </a>
            </li>
            {%empty%}
            <li>
                Entry List is Empty!
            </li>
        {% endfor %}

    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}
<!DOCTYPE html>



<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'query:search'%}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href = "{% url 'query:create_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href = "{% url 'query:random_page' %}">Random Page</a>

                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/massage.html
{%extends "encyclopedia/layout.html"%}

{% block title %}
{{title}}
{% endblock %}

{% block body %}
<h1>{{massage}}</h1>
{% endblock%}

encyclopedia/templates/encyclopedia/showpage.html
{% extends "encyclopedia/layout.html" %}
        
{% block title %}
    {{title}}
{% endblock %}

           
{% block body %}
    <div> {{content|safe}} </div>

    <div>
        <form method = "GET" action = " {%url 'query:edit_page'%}"> {%csrf_token%}
            <input type="hidden" name="title" value="{{title}}">
            <input class = "btn btn-primary" type = "submit" value = "Update Content">
        </form>
    </div>    
{% endblock %}